---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
  {{- if .Values.tap.labels }}
    {{- toYaml .Values.tap.labels | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.tap.annotations }}
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  name: kubeshark-hub
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: kubeshark-hub
      port: 80
      targetPort: 80
  selector:
    app: kubeshark-hub
  type: NodePort
status:
  loadBalancer: {}
