---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: kubeshark-front
  {{- if .Values.tap.labels }}
    {{- toYaml .Values.tap.labels | nindent 4 }}
  {{- end }}
  annotations:
  {{- if .Values.tap.annotations }}
    {{- toYaml .Values.tap.annotations | nindent 4 }}
  {{- end }}
  name: kubeshark-front
  namespace: {{ .Release.Namespace }}
spec:
  containers:
    - env:
        - name: REACT_APP_DEFAULT_FILTER
          value: ' '
        - name: REACT_APP_HUB_HOST
          value: ' '
        - name: REACT_APP_HUB_PORT
          value: '{{ .Values.tap.ingress.enabled | ternary "/api" (print ":" .Values.tap.proxy.hub.port) }}'
      image: '{{ .Values.tap.docker.registry }}/front:{{ .Values.tap.docker.tag }}'
      imagePullPolicy: {{ .Values.tap.docker.imagepullpolicy }}
      name: kubeshark-front
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 1
        successThreshold: 1
        tcpSocket:
          port: 80
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 750m
          memory: 1Gi
        requests:
          cpu: 50m
          memory: 50Mi
  dnsPolicy: ClusterFirstWithHostNet
  serviceAccountName: kubeshark-service-account
  terminationGracePeriodSeconds: 0
  tolerations:
    - effect: NoExecute
      operator: Exists
{{- if not .Values.tap.ignoretainted }}
    - effect: NoSchedule
      operator: Exists
{{- end }}
status: {}
